language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
  - npm start -- --silent &
  - cypress run --record --parallel --key 9b22f9f4-14fa-4210-a961-4c912e6b41d6