language: node_js
node_js:
  - 8
cache:
  npm: true # this cashes ~/.npm folder on Travis
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
script:
  - npm run build
  - npm test
  - npm start -- --silent &
  - cypress run --record --parallel --key 9b22f9f4-14fa-4210-a961-4c912e6b41d6