// flow-typed signature: 4d40c6d3bd08704851b563f268471a49
// flow-typed version: <<STUB>>/eslint-find-rules_v3.1.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-find-rules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-find-rules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-find-rules/dist/bin/diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/dist/bin/find' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/dist/lib/array-diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/dist/lib/cli-util' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/dist/lib/flatten-rules-diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/dist/lib/object-diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/dist/lib/rule-finder' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/dist/lib/sort-rules' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/dist/lib/stringify-rule-config' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/src/bin/diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/src/bin/find' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/src/lib/array-diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/src/lib/cli-util' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/src/lib/flatten-rules-diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/src/lib/object-diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/src/lib/rule-finder' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/src/lib/sort-rules' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/src/lib/stringify-rule-config' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/bin/diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/bin/find' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/fixtures/no-path/index' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/lib/array-diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/lib/cli-util' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/lib/flatten-rules-diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/lib/object-diff' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/lib/rule-finder' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/lib/sort-rules' {
  declare module.exports: any;
}

declare module 'eslint-find-rules/test/lib/stringify-rule-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-find-rules/dist/bin/diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/dist/bin/diff'>;
}
declare module 'eslint-find-rules/dist/bin/find.js' {
  declare module.exports: $Exports<'eslint-find-rules/dist/bin/find'>;
}
declare module 'eslint-find-rules/dist/lib/array-diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/dist/lib/array-diff'>;
}
declare module 'eslint-find-rules/dist/lib/cli-util.js' {
  declare module.exports: $Exports<'eslint-find-rules/dist/lib/cli-util'>;
}
declare module 'eslint-find-rules/dist/lib/flatten-rules-diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/dist/lib/flatten-rules-diff'>;
}
declare module 'eslint-find-rules/dist/lib/object-diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/dist/lib/object-diff'>;
}
declare module 'eslint-find-rules/dist/lib/rule-finder.js' {
  declare module.exports: $Exports<'eslint-find-rules/dist/lib/rule-finder'>;
}
declare module 'eslint-find-rules/dist/lib/sort-rules.js' {
  declare module.exports: $Exports<'eslint-find-rules/dist/lib/sort-rules'>;
}
declare module 'eslint-find-rules/dist/lib/stringify-rule-config.js' {
  declare module.exports: $Exports<'eslint-find-rules/dist/lib/stringify-rule-config'>;
}
declare module 'eslint-find-rules/src/bin/diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/src/bin/diff'>;
}
declare module 'eslint-find-rules/src/bin/find.js' {
  declare module.exports: $Exports<'eslint-find-rules/src/bin/find'>;
}
declare module 'eslint-find-rules/src/lib/array-diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/src/lib/array-diff'>;
}
declare module 'eslint-find-rules/src/lib/cli-util.js' {
  declare module.exports: $Exports<'eslint-find-rules/src/lib/cli-util'>;
}
declare module 'eslint-find-rules/src/lib/flatten-rules-diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/src/lib/flatten-rules-diff'>;
}
declare module 'eslint-find-rules/src/lib/object-diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/src/lib/object-diff'>;
}
declare module 'eslint-find-rules/src/lib/rule-finder.js' {
  declare module.exports: $Exports<'eslint-find-rules/src/lib/rule-finder'>;
}
declare module 'eslint-find-rules/src/lib/sort-rules.js' {
  declare module.exports: $Exports<'eslint-find-rules/src/lib/sort-rules'>;
}
declare module 'eslint-find-rules/src/lib/stringify-rule-config.js' {
  declare module.exports: $Exports<'eslint-find-rules/src/lib/stringify-rule-config'>;
}
declare module 'eslint-find-rules/test/bin/diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/bin/diff'>;
}
declare module 'eslint-find-rules/test/bin/find.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/bin/find'>;
}
declare module 'eslint-find-rules/test/fixtures/no-path/index.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/fixtures/no-path/index'>;
}
declare module 'eslint-find-rules/test/lib/array-diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/lib/array-diff'>;
}
declare module 'eslint-find-rules/test/lib/cli-util.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/lib/cli-util'>;
}
declare module 'eslint-find-rules/test/lib/flatten-rules-diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/lib/flatten-rules-diff'>;
}
declare module 'eslint-find-rules/test/lib/object-diff.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/lib/object-diff'>;
}
declare module 'eslint-find-rules/test/lib/rule-finder.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/lib/rule-finder'>;
}
declare module 'eslint-find-rules/test/lib/sort-rules.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/lib/sort-rules'>;
}
declare module 'eslint-find-rules/test/lib/stringify-rule-config.js' {
  declare module.exports: $Exports<'eslint-find-rules/test/lib/stringify-rule-config'>;
}
