// flow-typed signature: cbd6412341f28d1040161922dbbbd13b
// flow-typed version: <<STUB>>/react-slider_v0.9.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-slider/react-slider' {
  declare module.exports: any;
}

declare module 'react-slider/stories/Button' {
  declare module.exports: any;
}

declare module 'react-slider/stories/index' {
  declare module.exports: any;
}

declare module 'react-slider/stories/ReactSlider' {
  declare module.exports: any;
}

declare module 'react-slider/stories/Welcome' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-slider/react-slider.js' {
  declare module.exports: $Exports<'react-slider/react-slider'>;
}
declare module 'react-slider/stories/Button.js' {
  declare module.exports: $Exports<'react-slider/stories/Button'>;
}
declare module 'react-slider/stories/index.js' {
  declare module.exports: $Exports<'react-slider/stories/index'>;
}
declare module 'react-slider/stories/ReactSlider.js' {
  declare module.exports: $Exports<'react-slider/stories/ReactSlider'>;
}
declare module 'react-slider/stories/Welcome.js' {
  declare module.exports: $Exports<'react-slider/stories/Welcome'>;
}
