// flow-typed signature: 65a825d2f08975f117714deeee1ddb8c
// flow-typed version: <<STUB>>/video-time_v1.1.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'video-time'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'video-time' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'video-time/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'video-time/index' {
  declare module.exports: $Exports<'video-time'>;
}
declare module 'video-time/index.js' {
  declare module.exports: $Exports<'video-time'>;
}
declare module 'video-time/test.js' {
  declare module.exports: $Exports<'video-time/test'>;
}
